<?php

declare(strict_types=1);

/**
 * @file
 * Provides an ai validations entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function ai_content_validation_theme(): array {
  return [
    'ai_content_validation_item' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for ai validations templates.
 *
 * Default template: ai-content-validation-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the ai validations information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ai_content_validation_item(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function ai_content_validation_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish ai validationss.
      $storage = \Drupal::entityTypeManager()->getStorage('ai_content_validation_item');
      $ai_content_validation_item_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($ai_content_validation_item_ids) as $ai_content_validation_item) {
        $ai_content_validation_item->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize ai validationss.
      $storage = \Drupal::entityTypeManager()->getStorage('ai_content_validation_item');
      $ai_content_validation_item_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($ai_content_validation_item_ids) as $ai_content_validation_item) {
        $ai_content_validation_item->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function ai_content_validation_user_predelete(UserInterface $account): void {
  // Delete ai validationss that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('ai_content_validation_item');
  $ai_content_validation_item_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($ai_content_validation_item_ids)
  );
}
